### ISSUE TITLE
Difficulty installing Music Mixing Style Transfer (Linux and Windows)

### ISSUE THREAD

**Issue by playdasegunda** [jhtonyKoo/music_mixing_style_transfer#2]
Hello, I am trying to create a colab for Music Mixing Style Transfer, but I am receiving the following error:

```
ERROR: Could not find a version that satisfies the requirement pymixconsole==0.0.1 (from versions: none)
ERROR: No matching distribution found for pymixconsole==0.0.1
```

**Colab**: [https://colab.research.google.com/drive/1xjhfPaXrRBWjsik4o9BGaSHtcTN7vfHr?usp=sharing](https://colab.research.google.com/drive/1xjhfPaXrRBWjsik4o9BGaSHtcTN7vfHr?usp=sharing)

I have tried removing the version "==0.0.1" and leaving only "pymixconsole", but the error remains.

How could I be solving this problem?

Note, I have already tried installing MMST on Windows, but I received exactly the same problem, I have not yet discovered the reason for the error and how to solve it.

We await your response, in advance my thanks.

Sincerely,
Lucas Rodrigues.

**Comment by jhtonyKoo** [comment]
Hello Lucas,

Thank you for pointing this issue out. The installation command for pymixconsole is actually as follows:
`pip install git+https://github.com/csteinmetz1/pymixconsole`
which can be found at the official repository of the "pymixconsole": https://github.com/csteinmetz1/pymixconsole

I have now fixed the "requirements.txt" file to address this issue. Please let me know if there are any other issues to run the code.

**Comment by playdasegunda** [comment]
> Hello Lucas,
> 
> Thank you for pointing this issue out. The installation command for pymixconsole is actually as follows: `pip install git+https://github.com/csteinmetz1/pymixconsole` which can be found at the official repository of the "pymixconsole": https://github.com/csteinmetz1/pymixconsole
> 
> I have now fixed the "requirements.txt" file to address this issue. Please let me know if there are any other issues to run the code.

thanks, fixed it, now this other error happened:

ERROR: Could not find a version that satisfies the requirement torch==1.8.1+cu111 (from versions: 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1)
ERROR: No matching distribution found for torch==1.8.1+cu111

**Comment by jhtonyKoo** [comment]
Hello Lucas, thanks for checking this.
I have now tested with the "requirements.txt" and I hope this installation process works now :)

**Comment by playdasegunda** [comment]
Hello everything is fine? I tried to install, and now apparently it worked, but in the inference step, I'm getting this error:

```
Traceback (most recent call last):
  File "inference/style_transfer.py", line 22, in <module>
    from networks import FXencoder, TCNModel
  File "/content/music_mixing_style_transfer/mixing_style_transfer/networks/__init__.py", line 1, in <module>
    from .architectures import *
  File "/content/music_mixing_style_transfer/mixing_style_transfer/networks/architectures.py", line 75, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/metrics/utils.py", line 29, in <module>
    from pytorch_lightning.utilities import rank_zero_deprecation
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/apply_func.py", line 28, in <module>
    if _compare_version("torchtext", operator.ge, "0.9.0"):
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/imports.py", line 53, in _compare_version
    pkg = importlib.import_module(package)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/dist-packages/torchtext/__init__.py", line 6, in <module>
    from torchtext import _extension  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
  File "/usr/local/lib/python3.8/dist-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
  File "/usr/local/lib/python3.8/dist-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
  File "/usr/local/lib/python3.8/dist-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.8/dist-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN5torch6detail10class_baseC2ERKSsS3_SsRKSt9type_infoS6_
```

what I researched has to do with torchtext..

Log error in colab: https://colab.research.google.com/drive/1xjhfPaXrRBWjsik4o9BGaSHtcTN7vfHr?usp=sharing

**Comment by jhtonyKoo** [comment]
Hello Lucas,

Could you try installing one of the following versions of torchtext?
`pip install torchtext==0.9.1`
`pip install torchtext==0.8.0`

I'm not so sure of the environment that you're using, so it would be great if you could check which version makes this work.

**Comment by sai-soum** [comment]
Hello,

I'm having trouble installing the repository. I am unable to install soxbindings and as I checked on internet, the builds for several versions of soxbindings have been failing lately. 
<img width="834" alt="image" src="https://user-images.githubusercontent.com/79447355/226589682-14e39819-0d78-4323-95ff-7b4f3d850604.png">

**Comment by jhtonyKoo** [comment]
Hello Soumya,

Thanks for bringing this up, the commands I used to install soxbindings were as below (from [here](https://pysox.readthedocs.io/en/latest/#installation)):
`$ apt-get install libsox-fmt-all`
`$ apt-get install sox`
`$ pip install sox`

If this is the way that you've tried and didn't work, could you please also refer me to the site that reported this issue?
